=== vjachesl/javaStudy-task3/xml/knifes2.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            elementFormDefault="qualified" attributeFormDefault="unqualified">

    <!-- Root Element-->
    <xsd:element name="knifes">
        <xsd:complexType>
            <xsd:sequence>

                <!-- Included unbounded instances of knifes-->
                <xsd:element name="knife" type="knifeDesc" minOccurs="0"
                             maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <!-- Define of type Knife Description-->
    <xsd:complexType name="knifeDesc">
        <xsd:sequence>
            <xsd:element name="knifeType">

                <!-- Define Knifes types with restriction -->
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:enumeration value="knife"/>
                        <xsd:enumeration value="dagger"/>
                        <xsd:enumeration value="saber"/>
                        <xsd:enumeration value="sword"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>

            <!-- Define the handy parametr with restriction for one or two-->
            <xsd:element name="knifeHandy">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:integer">
                        <xsd:minInclusive value="1"/>
                        <xsd:maxInclusive value="2"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <!-- Define Country of origin as regular string -->
            <xsd:element name="knifeOrigin" type="xsd:string"/>

            <!-- Define group of parametrs Visual-->
            <xsd:element name="knifeVisual">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="knifeBlade">
                            <xsd:complexType>
                                <xsd:attribute name="length" type="bladeSize" use="required"/>
                                <xsd:attribute name="width" type="bladeSize" use="required"/>
                                <xsd:attribute name="metal" type="metalType" use="required"/>
                            </xsd:complexType>
                        </xsd:element>
                        <xsd:element name="knifeHandle">
                            <xsd:complexType>
                                <xsd:choice>
                                    <xsd:element name="wood">
                                        <xsd:complexType>
                                            <xsd:attribute name="type" type="woodType" use="required">
                                            </xsd:attribute>
                                        </xsd:complexType>
                                    </xsd:element>
                                    <xsd:element name="leatherCoated"/>
                                    <xsd:element name="plastic"/>
                                </xsd:choice>
                            </xsd:complexType>
                        </xsd:element>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="collection" type="xsd:boolean"/>
        </xsd:sequence>
        <xsd:attribute name="name" type="xsd:ID"/>
    </xsd:complexType>

    <!-- Blade size type definition with restriction -->
    <xsd:simpleType name="bladeSize">
        <xsd:restriction base="xsd:integer">
            <xsd:minInclusive value="10"/>
        </xsd:restriction>
    </xsd:simpleType>

    <!-- Blade metal definition with restriction -->
    <xsd:simpleType name="metalType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="steel"/>
            <xsd:enumeration value="copper"/>
            <xsd:enumeration value="iron"/>
        </xsd:restriction>
    </xsd:simpleType>

    <!-- Handle wood material type definition with restriction -->
    <xsd:simpleType name="woodType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="oak"/>
            <xsd:enumeration value="acacia"/>
            <xsd:enumeration value="walnut"/>
        </xsd:restriction>
    </xsd:simpleType>

</xsd:schema>

=== vjachesl/javaStudy-task3/xml/knifes.xml
<?xml version="1.0" encoding="utf-8"?>
<knifes xsi:noNamespaceSchemaLocation="knifes2.xsd"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <!-- 1 Element-->
    <knife name="tourist">
        <knifeType>knife</knifeType>
        <knifeHandy>1</knifeHandy>
        <knifeOrigin>China</knifeOrigin>
        <knifeVisual>
            <knifeBlade length="10" width="20" metal="steel"/>
            <knifeHandle>
                <plastic/>
            </knifeHandle>
        </knifeVisual>
        <collection>false</collection>
    </knife>

    <!-- 2 Element-->
    <knife name="machete">
        <knifeType>knife</knifeType>
        <knifeHandy>1</knifeHandy>
        <knifeOrigin>China</knifeOrigin>
        <knifeVisual>
            <knifeBlade length="90" width="20" metal="steel"></knifeBlade>
            <knifeHandle>
                <wood type="acacia"></wood>
            </knifeHandle>
        </knifeVisual>
        <collection>false</collection>
    </knife>

    <!-- 3 Element-->
    <knife name="KingsSword">
        <knifeType>sword</knifeType>
        <knifeHandy>2</knifeHandy>
        <knifeOrigin>Ukraine</knifeOrigin>
        <knifeVisual>
            <knifeBlade length="120" width="30" metal="steel"></knifeBlade>
            <knifeHandle>
                <leatherCoated/>
            </knifeHandle>
        </knifeVisual>
        <collection>false</collection>
    </knife>
</knifes>
